services:
  postgres:
    image: docker.bintray.io/postgres:15.6-alpine
    container_name: artifactorydb
    user: "$UID:$GID"
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.71.5
    container_name: artifactory
    user: "$UID:$GID"
    environment:
      # - EXTRA_JAVA_OPTIONS=-Xms4g -Xmx4g
      - ENABLE_MIGRATION=y
      - JF_SHARED_DATABASE_TYPE=postgresql
      - JF_SHARED_DATABASE_USERNAME=artifactory
      - JF_SHARED_DATABASE_PASSWORD=password
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://artifactorydb:5432/artifactory
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
    ports:
      - 8082:8082 # for router communication
      - 8081:8081 # for artifactory communication
      - 8085:8085 # for artifactory federation communication
    depends_on:
      - postgres
    volumes:
      - ./var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory
